#!/usr/bin/env python

import sys
import os
import os.path
import shutil

def main(argv):
    fname = str(argv[0])
    versionDir = os.getcwd() + "/.versiondir"
    version = argv[1]
    path = versionDir + '/' + fname + "." + version
    with open(path) as f:
        content = f.read().replace('\n','')
        print content

if __name__ == "__main__":
    main(sys.argv[1:])    
