#!/usr/bin/env python

import sys
import os
import os.path

def main(argv):
    fname = str(argv[0])
    versionDir = os.getcwd() + "/.versiondir"
    fname = os.path.join(versionDir,fname)
    for i in range(1,7):
        if os.path.exists(fname + "." + str(i)):
            version =  fname + "." + str(i)
            print os.path.basename(version)


if __name__ == "__main__":
    main(sys.argv[1:])    
