#!/usr/bin/env python

import sys
import os
import os.path
import shutil

def main(argv):
    fname = str(argv[0])
    versionDir = os.getcwd() + "/.versiondir"
    version = int(argv[1])
    fname = os.path.join(versionDir,fname)
    replace = fname + "." + str(version)
    temp0 = fname + ".0"
    shutil.copyfile(replace,temp0)
    for i in range(version-1,0,-1):
        tmp = fname + "." + str(i)
        tmp1 = fname + "." + str(i+1)
        shutil.copyfile(tmp,tmp1)
    shutil.copyfile(temp0,fname + ".1")


if __name__ == "__main__":
    main(sys.argv[1:])    
