#!/usr/bin/env python

import sys
import os
import os.path
import shutil

def main(argv):
    fname = str(argv[0])
    versionDir = os.getcwd() + "/.versiondir"
    path = os.path.join(versionDir,fname)
    for i in range(2,7):
        remPath = path+"."+str(i)
        if os.path.exists(remPath):
            os.remove(remPath)


if __name__ == "__main__":
    main(sys.argv[1:])    
