#!/usr/bin/env python

import sys
import os
import os.path
from shutil import rmtree

def main(argv):
    versionDir = os.getcwd() + "/.versiondir"
    rmtree(versionDir)
    os.system("fusermount -u mount")


if __name__ == "__main__":
    main(sys.argv[1:])    
